spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}

gauth:
  clientId: ${GAUTH_CLIENT}
  clientSecret: ${GAUTH_SECRET}
  redirectUri: ${GAUTH_REDIRECT_URI}