spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}

gauth:
  clientId: ${GAUTH_CLIENT}
  clientSecret: ${GAUTH_SECRET}
  redirectUri: ${GAUTH_REDIRECT_URI}

