name: CI

on:
  pull_request:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle (without tests)
        run: ./gradlew clean build -x test --no-daemon

      - name: MindWay Server CI success Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ MindWay Server CI success ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK_BOT }}
          color: 00FF00

      - name: MindWay Server CI failed Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❌ MindWay Server CI failed ❌
          webhook: ${{ secrets.DISCORD_WEBHOOK_BOT }}
          color: FF0000