name: Build with Gradle and Run Docker Container

on:
  push:
    branches: ["158-fix-stuck-at-docker-build"]
  pull_request:
    branches: ["158-fix-stuck-at-docker-build"]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: sudo su
        run: sudo su && echo -n ${{ secrets.SELFHOSTED_PASSWORD }} | sudo -S

      - name: docker image build
        run: sudo docker build -t mindway-v2-backend .

      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2> /dev/null || true

      - name: docker run new container
        run: sudo docker run --name mindwayv2container --env-file /home/minjun/.env --rm -d -p 10000:8080 mindway-v2-backend

      - name: delete old docker image
        run: sudo docker system prune -f
