name: Build with Gradle and Upload DockerImage to DockerHub

on:
  push:
    branches: ["154-githubactions-docker-release"]
  pull_request:
    branches: ["154-githubactions-docker-release"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: tag docker image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend:latest

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend

  run-docker-image:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: Check current user
        run: whoami

      - name: Add user to Docker group
        run: |
          sudo usermod -aG docker $(whoami)
          newgrp docker

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Check Docker login status
        run: sudo docker info

      - name: pull docker image with latest tag
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend:latest

      - name: docker stop container
        run: sudo docker stop $(sudo docker ps -q) 2> /dev/null || true

      - name: docker run new container
        run: sudo docker run --name mindwayv2container --env-file .env.list --rm -d -p 10000:8080 ${{ secrets.DOCKERHUB_USERNAME }}/mindway-v2-backend

      - name: delete old docker image
        run: sudo docker system prune -f
